# Generated by Django 4.2.19 on 2025-03-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('ops', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('mlbid', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.teammodel')),
            ],
        ),
        migrations.CreateModel(
            name='PitcherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.FloatField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='HitterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_average', models.FloatField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('rbis', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseballapp.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('date', models.DateField(default='2000-01-01')),
                ('game_pk', models.IntegerField(default=-1)),
                ('away_starting_pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_starting_pitcher', to='baseballapp.pitchermodel')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='baseballapp.teammodel')),
                ('home_starting_pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_starting_pitcher', to='baseballapp.pitchermodel')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='baseballapp.teammodel')),
            ],
        ),
    ]
