# Generated by Django 4.2.19 on 2025-03-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseballapp.teammodel'),
        ),
    ]
