# Generated by Django 4.2.19 on 2025-02-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
